name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test -- --coverage 
 
      - run: docker build -t mrwizzard82/multi-client-10-14 ./client
      - run: docker build -t mrwizzard82/multi-nginx-10-14 ./nginx
      - run: docker build -t mrwizzard82/multi-server-10-14 ./server
      - run: docker build -t mrwizzard82/multi-worker-10-14 ./worker
 
      - run: docker push mrwizzard82/multi-client-10-14
      - run: docker push mrwizzard82/multi-nginx-10-14
      - run: docker push mrwizzard82/multi-server-10-14
      - run: docker push mrwizzard82/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-533267013190
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip